### ISSUE TITLE
How I can pass the scope in authorization URL

### ISSUE THREAD

**Issue by dhavalpatel4** [ramsey/laravel-oauth2-instagram#4]
Hi Ramsey, I want to pass scope=likes, comments, public_content in authorization URL can you give me some example?

**Comment by ramsey** [comment]
The first parameter to `Instagram::authorize()` is an array of options you can pass to configure the authorization URL:

``` php
$authUrl = Instagram::authorize([
    'scope' => ['basic', 'likes', 'comments'],
]);
```

For more information, see [here](https://github.com/thephpleague/oauth2-instagram#managing-scopes) and [here](https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/AbstractProvider.php#L359-L379).

**Comment by dhavalpatel4** [comment]
Thanks, Ben it worked 👍
